server:
  port: 8084

spring:
  application:
    name: lesson-service
  datasource:
    url: ${LESSON_DB_URL}
    username: ${LESSON_DB_USERNAME}
    password: ${LESSON_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: lesson-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
      concurrency: 1
      trusted-packages: org.sleepless_artery.lesson_service.*
      
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6383

grpc:
  client:
    course-service:
      address: "static://localhost:9095"
      negotiation-type: plaintext
    
management:
  endpoint:
    web:
      exposure:
        include: health,info
      health:
        show-details: always
      base-path: /internal/actuator
  endpoint:
    health:
      show-details: always