spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        generate_statistics: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    org:
      springframework: DEBUG
      hibernate:
        SQL: DEBUG
        type.descriptor.sql.BasicBinder: TRACE
      sleepless_artery: DEBUG
    com.zaxxer.hikari: DEBUG