server:
  port: 8085

spring:
  datasource:
    url: ${AUTH_DB_URL}
    username: ${AUTH_DB_USERNAME}
    password: ${AUTH_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  kafka:
    producer:
      bootstrap-servers: host.docker.internal:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 5
      acks: all
      batch-size: 65536
      delivery-timeout-ms: 30000
      linger-ms: 1000
      request-timeout-ms: 10000
      retry-backoff-ms: 1000
      properties:
        enable.idempotence: true
    consumer:
      bootstrap-servers: host.docker.internal:9092
      group-id: auth-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
      type-mappings: credential:org.sleepless_artery.auth_service.dto.credentialDto
      concurrency: 1
      trusted-packages: org.sleepless_artery.auth_service.*
    topic:
      prefix: auth
      domain: users
      partitions: 1
      replicas: 1
      minInsyncReplicas: 1

management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: ${MANAGEMENT_ENDPOINTS_BASE_PATH:/actuator}
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true

jwt:
  secret: ${JWT_SECRET:default-secret-key}
  lifetime: ${JWT_LIFETIME:6h}

admin:
  email-address: ${ADMIN_EMAIL_ADDRESS}
  password: ${ADMIN_PASSWORD}

grpc:
  client:
    user-auth-api-service:
      address: 'static://localhost:9090'