server:
  port: 8085

spring:
  application:
    name: enrollment-service
  datasource:
    url: ${ENROLLMENT_DB_URL}
    username: ${ENROLLMENT_DB_USERNAME}
    password: ${ENROLLMENT_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:29092}
      group-id: enrollment-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
      concurrency: 1
      
  cache:
    type: redis
  data:
    redis:
      host: ${ENROLLMENTS_REDIS_HOST:redis-enrollments}
      port: ${ENROLLMENTS_REDIS_PORT:6379}

grpc:
  server:
    port: 9099
  client:
    GLOBAL:
      negotiation-type: plaintext
      keep-alive-time: 30s
      keep-alive-timeout: 20s
      deadline-after: 10s
    user-service:
      address: ${USER_SERVICE_GRPC_URL:static://user-service:9093}
    course-service:
      address: ${COURSE_SERVICE_GRPC_URL:static://course-service:9095}
    
management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /internal/actuator
  endpoint:
    health:
      show-details: always
